name: Trigger docs deploy on specific branch release
run-name: Triggering docs deploy on ${{ github.event.client_payload.branch }} branch release
on:
  repository_dispatch:
    types: az_bootstrap_release
jobs:
  deploy-docs-for-v2-release:
    if: ${{ github.event.client_payload.branch  == '2.x' }}
    uses: "az-digital/digital.arizona.edu/.github/workflows/deploy-docs-for-v2-release.yml@main"
    secrets: inherit
    with:
      sha: ${{ github.event.client_payload.sha }}
      ref: ${{ github.event.client_payload.ref }}
      version: ${{ github.event.client_payload.version }}
  deploy-docs-for-v5-release:
    if: ${{ github.event.client_payload.branch == 'main' }}
    uses: "az-digital/digital.arizona.edu/.github/workflows/deploy-docs-for-v5-release.yml@main"
    secrets: inherit
    with:
      sha: ${{ github.event.client_payload.sha }}
      ref: ${{ github.event.client_payload.ref }}
      version: ${{ github.event.client_payload.version }}
